services:
  - type: web
    name: prestige-shop-frontend
    env: static
    buildCommand: echo "Building static site"
    startCommand: echo "Serving static site"
    staticPublishPath: ./
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16