services:
  - type: web
    name: prestige-shop-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 60 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16